//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eConnect.IntegrationService
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IncrementDecrement", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
    public enum IncrementDecrement : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Decrement = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Increment = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eConnectSqlFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
    public partial class eConnectSqlFault : object
    {
        
        private eConnectSqlErrorCollection ErrorsField;
        
        private string MessageField;
        
        private string StackTraceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public eConnectSqlErrorCollection Errors
        {
            get
            {
                return this.ErrorsField;
            }
            set
            {
                this.ErrorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace
        {
            get
            {
                return this.StackTraceField;
            }
            set
            {
                this.StackTraceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="eConnectSqlErrorCollection", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect", ItemName="eConnectSqlError")]
    public class eConnectSqlErrorCollection : System.Collections.Generic.List<eConnectSqlError>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eConnectSqlError", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
    public partial class eConnectSqlError : object
    {
        
        private byte ClassField;
        
        private byte ErrorClassField;
        
        private int LineNumberField;
        
        private string MessageField;
        
        private int NumberField;
        
        private string ProcedureField;
        
        private string ServerField;
        
        private string SourceField;
        
        private byte StateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Class
        {
            get
            {
                return this.ClassField;
            }
            set
            {
                this.ClassField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte ErrorClass
        {
            get
            {
                return this.ErrorClassField;
            }
            set
            {
                this.ErrorClassField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LineNumber
        {
            get
            {
                return this.LineNumberField;
            }
            set
            {
                this.LineNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number
        {
            get
            {
                return this.NumberField;
            }
            set
            {
                this.NumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Procedure
        {
            get
            {
                return this.ProcedureField;
            }
            set
            {
                this.ProcedureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Server
        {
            get
            {
                return this.ServerField;
            }
            set
            {
                this.ServerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source
        {
            get
            {
                return this.SourceField;
            }
            set
            {
                this.SourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eConnectFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
    public partial class eConnectFault : object
    {
        
        private string ExceptionTypeField;
        
        private string MessageField;
        
        private string SourceField;
        
        private string StackTraceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionType
        {
            get
            {
                return this.ExceptionTypeField;
            }
            set
            {
                this.ExceptionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source
        {
            get
            {
                return this.SourceField;
            }
            set
            {
                this.SourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace
        {
            get
            {
                return this.StackTraceField;
            }
            set
            {
                this.StackTraceField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RMPaymentType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
    public enum RMPaymentType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RMInvoices = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RMScheduledPayments = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RMDebitMemos = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RMFinanceCharges = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RMServiceRepairs = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RMWarranty = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RMCreditMemo = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RMReturn = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RMPayments = 9,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IVDocType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
    public enum IVDocType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IVAdjustment = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IVVariance = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IVTransfer = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SopType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
    public enum SopType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SOPQuote = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SOPOrder = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SOPInvoice = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SOPReturn = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SOPBackOrder = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RollBackDocument", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
    public partial class RollBackDocument : object
    {
        
        private string DocumentIDField;
        
        private string DocumentNumberField;
        
        private TransactionType DocumentTransactionTypeField;
        
        private System.Nullable<short> DocumentTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentID
        {
            get
            {
                return this.DocumentIDField;
            }
            set
            {
                this.DocumentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentNumber
        {
            get
            {
                return this.DocumentNumberField;
            }
            set
            {
                this.DocumentNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TransactionType DocumentTransactionType
        {
            get
            {
                return this.DocumentTransactionTypeField;
            }
            set
            {
                this.DocumentTransactionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> DocumentType
        {
            get
            {
                return this.DocumentTypeField;
            }
            set
            {
                this.DocumentTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
    public enum TransactionType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SOP = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GL = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RM = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PM = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        POP = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        POPReceipt = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IVTrans = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IVTransfer = 7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/dynamics/gp/2010/01", ConfigurationName="eConnect")]
    public interface eConnect
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextPOP" +
            "ReceiptNumber", ReplyAction="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextPOP" +
            "ReceiptNumberResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectSqlFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextPOP" +
            "ReceiptNumbereConnectSqlFaultFault", Name="eConnectSqlFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextPOP" +
            "ReceiptNumbereConnectFaultFault", Name="eConnectFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        System.Threading.Tasks.Task<string> GetNextPOPReceiptNumberAsync(IncrementDecrement incdec, string databaseConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextGLJ" +
            "ournalEntryNumber", ReplyAction="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextGLJ" +
            "ournalEntryNumberResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectSqlFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextGLJ" +
            "ournalEntryNumbereConnectSqlFaultFault", Name="eConnectSqlFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextGLJ" +
            "ournalEntryNumbereConnectFaultFault", Name="eConnectFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        System.Threading.Tasks.Task<string> GetNextGLJournalEntryNumberAsync(IncrementDecrement incdec, string databaseConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextPON" +
            "umber", ReplyAction="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextPON" +
            "umberResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectSqlFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextPON" +
            "umbereConnectSqlFaultFault", Name="eConnectSqlFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextPON" +
            "umbereConnectFaultFault", Name="eConnectFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        System.Threading.Tasks.Task<string> GetNextPONumberAsync(IncrementDecrement incdec, string databaseConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextRMN" +
            "umber", ReplyAction="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextRMN" +
            "umberResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextRMN" +
            "umbereConnectFaultFault", Name="eConnectFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectSqlFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextRMN" +
            "umbereConnectSqlFaultFault", Name="eConnectSqlFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        System.Threading.Tasks.Task<string> GetNextRMNumberAsync(IncrementDecrement incdec, RMPaymentType documentType, string databaseConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetPMNextV" +
            "oucherNumber", ReplyAction="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetPMNextV" +
            "oucherNumberResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectSqlFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetPMNextV" +
            "oucherNumbereConnectSqlFaultFault", Name="eConnectSqlFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetPMNextV" +
            "oucherNumbereConnectFaultFault", Name="eConnectFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        System.Threading.Tasks.Task<string> GetPMNextVoucherNumberAsync(IncrementDecrement incdec, string databaseConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextIVN" +
            "umber", ReplyAction="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextIVN" +
            "umberResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextIVN" +
            "umbereConnectFaultFault", Name="eConnectFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectSqlFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextIVN" +
            "umbereConnectSqlFaultFault", Name="eConnectSqlFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        System.Threading.Tasks.Task<string> GetNextIVNumberAsync(IncrementDecrement incdec, IVDocType documentType, string databaseConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextSOP" +
            "Number", ReplyAction="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextSOP" +
            "NumberResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectSqlFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextSOP" +
            "NumbereConnectSqlFaultFault", Name="eConnectSqlFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextSOP" +
            "NumbereConnectFaultFault", Name="eConnectFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        System.Threading.Tasks.Task<string> GetNextSOPNumberAsync(IncrementDecrement incdec, string DOCIDKey, SopType documentType, string databaseConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/gp/2010/01/IDocumentNumberRollback/RollBack" +
            "Documents", ReplyAction="http://schemas.microsoft.com/dynamics/gp/2010/01/IDocumentNumberRollback/RollBack" +
            "DocumentsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectSqlFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/IDocumentNumberRollback/RollBack" +
            "DocumentseConnectSqlFaultFault", Name="eConnectSqlFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/IDocumentNumberRollback/RollBack" +
            "DocumentseConnectFaultFault", Name="eConnectFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        System.Threading.Tasks.Task<bool> RollBackDocumentsAsync(RollBackDocument[] documentNumberCollection, string databaseConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/gp/2010/01/eConnect/CreateEntity", ReplyAction="http://schemas.microsoft.com/dynamics/gp/2010/01/eConnect/CreateEntityResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/eConnect/CreateEntityeConnectFau" +
            "ltFault", Name="eConnectFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectSqlFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/eConnect/CreateEntityeConnectSql" +
            "FaultFault", Name="eConnectSqlFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        System.Threading.Tasks.Task<bool> CreateEntityAsync(string connectionString, string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/gp/2010/01/eConnect/CreateTransactionEntity" +
            "", ReplyAction="http://schemas.microsoft.com/dynamics/gp/2010/01/eConnect/CreateTransactionEntity" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/eConnect/CreateTransactionEntity" +
            "eConnectFaultFault", Name="eConnectFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectSqlFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/eConnect/CreateTransactionEntity" +
            "eConnectSqlFaultFault", Name="eConnectSqlFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        System.Threading.Tasks.Task<string> CreateTransactionEntityAsync(string connectionString, string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/gp/2010/01/eConnect/UpdateEntity", ReplyAction="http://schemas.microsoft.com/dynamics/gp/2010/01/eConnect/UpdateEntityResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectSqlFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/eConnect/UpdateEntityeConnectSql" +
            "FaultFault", Name="eConnectSqlFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/eConnect/UpdateEntityeConnectFau" +
            "ltFault", Name="eConnectFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        System.Threading.Tasks.Task<bool> UpdateEntityAsync(string connectionString, string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/gp/2010/01/eConnect/DeleteEntity", ReplyAction="http://schemas.microsoft.com/dynamics/gp/2010/01/eConnect/DeleteEntityResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectSqlFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/eConnect/DeleteEntityeConnectSql" +
            "FaultFault", Name="eConnectSqlFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/eConnect/DeleteEntityeConnectFau" +
            "ltFault", Name="eConnectFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        System.Threading.Tasks.Task<bool> DeleteEntityAsync(string connectionString, string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/gp/2010/01/eConnect/UpdateTransactionEntity" +
            "", ReplyAction="http://schemas.microsoft.com/dynamics/gp/2010/01/eConnect/UpdateTransactionEntity" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectSqlFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/eConnect/UpdateTransactionEntity" +
            "eConnectSqlFaultFault", Name="eConnectSqlFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/eConnect/UpdateTransactionEntity" +
            "eConnectFaultFault", Name="eConnectFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        System.Threading.Tasks.Task<bool> UpdateTransactionEntityAsync(string connectionString, string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/gp/2010/01/eConnect/DeleteTransactionEntity" +
            "", ReplyAction="http://schemas.microsoft.com/dynamics/gp/2010/01/eConnect/DeleteTransactionEntity" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectSqlFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/eConnect/DeleteTransactionEntity" +
            "eConnectSqlFaultFault", Name="eConnectSqlFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/eConnect/DeleteTransactionEntity" +
            "eConnectFaultFault", Name="eConnectFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        System.Threading.Tasks.Task<bool> DeleteTransactionEntityAsync(string connectionString, string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/gp/2010/01/eConnect/GetEntity", ReplyAction="http://schemas.microsoft.com/dynamics/gp/2010/01/eConnect/GetEntityResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectSqlFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/eConnect/GetEntityeConnectSqlFau" +
            "ltFault", Name="eConnectSqlFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/eConnect/GetEntityeConnectFaultF" +
            "ault", Name="eConnectFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        System.Threading.Tasks.Task<string> GetEntityAsync(string connectionString, string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/gp/2010/01/eConnect/Dispose", ReplyAction="http://schemas.microsoft.com/dynamics/gp/2010/01/eConnect/DisposeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectSqlFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/eConnect/DisposeeConnectSqlFault" +
            "Fault", Name="eConnectSqlFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/eConnect/DisposeeConnectFaultFau" +
            "lt", Name="eConnectFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        System.Threading.Tasks.Task DisposeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface eConnectChannel : eConnect, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class eConnectClient : System.ServiceModel.ClientBase<eConnect>, eConnect
    {
        
        public eConnectClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> GetNextPOPReceiptNumberAsync(IncrementDecrement incdec, string databaseConnectionString)
        {
            return base.Channel.GetNextPOPReceiptNumberAsync(incdec, databaseConnectionString);
        }
        
        public System.Threading.Tasks.Task<string> GetNextGLJournalEntryNumberAsync(IncrementDecrement incdec, string databaseConnectionString)
        {
            return base.Channel.GetNextGLJournalEntryNumberAsync(incdec, databaseConnectionString);
        }
        
        public System.Threading.Tasks.Task<string> GetNextPONumberAsync(IncrementDecrement incdec, string databaseConnectionString)
        {
            return base.Channel.GetNextPONumberAsync(incdec, databaseConnectionString);
        }
        
        public System.Threading.Tasks.Task<string> GetNextRMNumberAsync(IncrementDecrement incdec, RMPaymentType documentType, string databaseConnectionString)
        {
            return base.Channel.GetNextRMNumberAsync(incdec, documentType, databaseConnectionString);
        }
        
        public System.Threading.Tasks.Task<string> GetPMNextVoucherNumberAsync(IncrementDecrement incdec, string databaseConnectionString)
        {
            return base.Channel.GetPMNextVoucherNumberAsync(incdec, databaseConnectionString);
        }
        
        public System.Threading.Tasks.Task<string> GetNextIVNumberAsync(IncrementDecrement incdec, IVDocType documentType, string databaseConnectionString)
        {
            return base.Channel.GetNextIVNumberAsync(incdec, documentType, databaseConnectionString);
        }
        
        public System.Threading.Tasks.Task<string> GetNextSOPNumberAsync(IncrementDecrement incdec, string DOCIDKey, SopType documentType, string databaseConnectionString)
        {
            return base.Channel.GetNextSOPNumberAsync(incdec, DOCIDKey, documentType, databaseConnectionString);
        }
        
        public System.Threading.Tasks.Task<bool> RollBackDocumentsAsync(RollBackDocument[] documentNumberCollection, string databaseConnectionString)
        {
            return base.Channel.RollBackDocumentsAsync(documentNumberCollection, databaseConnectionString);
        }
        
        public System.Threading.Tasks.Task<bool> CreateEntityAsync(string connectionString, string xml)
        {
            return base.Channel.CreateEntityAsync(connectionString, xml);
        }
        
        public System.Threading.Tasks.Task<string> CreateTransactionEntityAsync(string connectionString, string xml)
        {
            return base.Channel.CreateTransactionEntityAsync(connectionString, xml);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateEntityAsync(string connectionString, string xml)
        {
            return base.Channel.UpdateEntityAsync(connectionString, xml);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteEntityAsync(string connectionString, string xml)
        {
            return base.Channel.DeleteEntityAsync(connectionString, xml);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateTransactionEntityAsync(string connectionString, string xml)
        {
            return base.Channel.UpdateTransactionEntityAsync(connectionString, xml);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteTransactionEntityAsync(string connectionString, string xml)
        {
            return base.Channel.DeleteTransactionEntityAsync(connectionString, xml);
        }
        
        public System.Threading.Tasks.Task<string> GetEntityAsync(string connectionString, string xml)
        {
            return base.Channel.GetEntityAsync(connectionString, xml);
        }
        
        public System.Threading.Tasks.Task DisposeAsync()
        {
            return base.Channel.DisposeAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/dynamics/gp/2010/01", ConfigurationName="ITransactionRecordIds")]
    public interface ITransactionRecordIds
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextPOP" +
            "ReceiptNumber", ReplyAction="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextPOP" +
            "ReceiptNumberResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectSqlFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextPOP" +
            "ReceiptNumbereConnectSqlFaultFault", Name="eConnectSqlFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextPOP" +
            "ReceiptNumbereConnectFaultFault", Name="eConnectFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        System.Threading.Tasks.Task<string> GetNextPOPReceiptNumberAsync(IncrementDecrement incdec, string databaseConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextGLJ" +
            "ournalEntryNumber", ReplyAction="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextGLJ" +
            "ournalEntryNumberResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectSqlFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextGLJ" +
            "ournalEntryNumbereConnectSqlFaultFault", Name="eConnectSqlFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextGLJ" +
            "ournalEntryNumbereConnectFaultFault", Name="eConnectFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        System.Threading.Tasks.Task<string> GetNextGLJournalEntryNumberAsync(IncrementDecrement incdec, string databaseConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextPON" +
            "umber", ReplyAction="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextPON" +
            "umberResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectSqlFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextPON" +
            "umbereConnectSqlFaultFault", Name="eConnectSqlFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextPON" +
            "umbereConnectFaultFault", Name="eConnectFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        System.Threading.Tasks.Task<string> GetNextPONumberAsync(IncrementDecrement incdec, string databaseConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextRMN" +
            "umber", ReplyAction="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextRMN" +
            "umberResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextRMN" +
            "umbereConnectFaultFault", Name="eConnectFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectSqlFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextRMN" +
            "umbereConnectSqlFaultFault", Name="eConnectSqlFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        System.Threading.Tasks.Task<string> GetNextRMNumberAsync(IncrementDecrement incdec, RMPaymentType documentType, string databaseConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetPMNextV" +
            "oucherNumber", ReplyAction="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetPMNextV" +
            "oucherNumberResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectSqlFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetPMNextV" +
            "oucherNumbereConnectSqlFaultFault", Name="eConnectSqlFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetPMNextV" +
            "oucherNumbereConnectFaultFault", Name="eConnectFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        System.Threading.Tasks.Task<string> GetPMNextVoucherNumberAsync(IncrementDecrement incdec, string databaseConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextIVN" +
            "umber", ReplyAction="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextIVN" +
            "umberResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextIVN" +
            "umbereConnectFaultFault", Name="eConnectFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectSqlFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextIVN" +
            "umbereConnectSqlFaultFault", Name="eConnectSqlFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        System.Threading.Tasks.Task<string> GetNextIVNumberAsync(IncrementDecrement incdec, IVDocType documentType, string databaseConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextSOP" +
            "Number", ReplyAction="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextSOP" +
            "NumberResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectSqlFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextSOP" +
            "NumbereConnectSqlFaultFault", Name="eConnectSqlFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/ITransactionRecordIds/GetNextSOP" +
            "NumbereConnectFaultFault", Name="eConnectFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        System.Threading.Tasks.Task<string> GetNextSOPNumberAsync(IncrementDecrement incdec, string DOCIDKey, SopType documentType, string databaseConnectionString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface ITransactionRecordIdsChannel : ITransactionRecordIds, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class TransactionRecordIdsClient : System.ServiceModel.ClientBase<ITransactionRecordIds>, ITransactionRecordIds
    {
        
        public TransactionRecordIdsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> GetNextPOPReceiptNumberAsync(IncrementDecrement incdec, string databaseConnectionString)
        {
            return base.Channel.GetNextPOPReceiptNumberAsync(incdec, databaseConnectionString);
        }
        
        public System.Threading.Tasks.Task<string> GetNextGLJournalEntryNumberAsync(IncrementDecrement incdec, string databaseConnectionString)
        {
            return base.Channel.GetNextGLJournalEntryNumberAsync(incdec, databaseConnectionString);
        }
        
        public System.Threading.Tasks.Task<string> GetNextPONumberAsync(IncrementDecrement incdec, string databaseConnectionString)
        {
            return base.Channel.GetNextPONumberAsync(incdec, databaseConnectionString);
        }
        
        public System.Threading.Tasks.Task<string> GetNextRMNumberAsync(IncrementDecrement incdec, RMPaymentType documentType, string databaseConnectionString)
        {
            return base.Channel.GetNextRMNumberAsync(incdec, documentType, databaseConnectionString);
        }
        
        public System.Threading.Tasks.Task<string> GetPMNextVoucherNumberAsync(IncrementDecrement incdec, string databaseConnectionString)
        {
            return base.Channel.GetPMNextVoucherNumberAsync(incdec, databaseConnectionString);
        }
        
        public System.Threading.Tasks.Task<string> GetNextIVNumberAsync(IncrementDecrement incdec, IVDocType documentType, string databaseConnectionString)
        {
            return base.Channel.GetNextIVNumberAsync(incdec, documentType, databaseConnectionString);
        }
        
        public System.Threading.Tasks.Task<string> GetNextSOPNumberAsync(IncrementDecrement incdec, string DOCIDKey, SopType documentType, string databaseConnectionString)
        {
            return base.Channel.GetNextSOPNumberAsync(incdec, DOCIDKey, documentType, databaseConnectionString);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/dynamics/gp/2010/01", ConfigurationName="IDocumentNumberRollback")]
    public interface IDocumentNumberRollback
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/gp/2010/01/IDocumentNumberRollback/RollBack" +
            "Documents", ReplyAction="http://schemas.microsoft.com/dynamics/gp/2010/01/IDocumentNumberRollback/RollBack" +
            "DocumentsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectSqlFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/IDocumentNumberRollback/RollBack" +
            "DocumentseConnectSqlFaultFault", Name="eConnectSqlFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        [System.ServiceModel.FaultContractAttribute(typeof(eConnectFault), Action="http://schemas.microsoft.com/dynamics/gp/2010/01/IDocumentNumberRollback/RollBack" +
            "DocumentseConnectFaultFault", Name="eConnectFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.GP.eConnect")]
        System.Threading.Tasks.Task<bool> RollBackDocumentsAsync(RollBackDocument[] documentNumberCollection, string databaseConnectionString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface IDocumentNumberRollbackChannel : IDocumentNumberRollback, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class DocumentNumberRollbackClient : System.ServiceModel.ClientBase<IDocumentNumberRollback>, IDocumentNumberRollback
    {
        
        public DocumentNumberRollbackClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> RollBackDocumentsAsync(RollBackDocument[] documentNumberCollection, string databaseConnectionString)
        {
            return base.Channel.RollBackDocumentsAsync(documentNumberCollection, databaseConnectionString);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
